module.exports =
  host: 'mongodb://localhost/socialcounts'
  limitResults: 100
  collectionName: 'social'
  mongoActive: true
  facebook: true
  twitter: true
  pinterest: true
  linkedin: true
  googlePlus: true
  stumbleUpon: true
  google_token: ''
